name: Code check
on:
  pull_request:
  push:
      branches:
        - main
jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/dev.txt --upgrade pip
      - name: Create fake .env file
        run: cp .env.template .env
      - name: Run codecheck
        run: bash scripts/codecheck.sh
      - name: Check api doc up to date
        run: scripts/create_doc.sh
      - name: Run tests
        run: bash -x scripts/run_tests.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'reports/junit.xml'
      - name: Post coverage report
        uses: 5monkeys/cobertura-action@v14
        with:
          path: reports/coverage.xml
          minimum_coverage: 75
      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
