name: Dependency locks

on:
  pull_request:

jobs:
  Linux-dependency-lockfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip-tools
        run: |
          python -m pip install -r requirements/lock/tools.lock --upgrade pip
      - name: Generate lock files
        run: bash scripts/gen-lock-files.sh
      - name: Archive lockfiles
        uses: actions/upload-artifact@v4
        with:
          name: linux-lock-files
          path: |
            diff-lock-linux.patch
            requirements/lock/linux/*
  Windows-dependency-lockfiles:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip-tools
        run: |
          python -m pip install -r requirements/lock/tools.lock --upgrade pip
      - name: Generate lock files
        run: bash scripts/gen-lock-files.sh
      - name: Archive lockfiles
        uses: actions/upload-artifact@v4
        with:
          name: windows-lock-files
          path: |
            diff-lock-win32.patch
            requirements/lock/win32/*

